/**
 * SidebarSpec — the display contract for the sidebar nav surface.
 *
 * Mirrors the ViewSpec pattern: vocabulary-driven, display-only,
 * generated by the AI agent and validated before rendering.
 * Hiding an item removes it from THIS user's sidebar only;
 * the workspace and its data are completely unaffected.
 */

/** One available nav item in the sidebar vocabulary. */
export interface SidebarNavItem {
  key: string;    // workspace id, e.g. 'engineering'
  label: string;  // default display label
}

/** The full set of items the AI may reference. Built from the app registry. */
export interface SidebarVocabulary {
  items: SidebarNavItem[];
}

/** One item entry in a user's persisted SidebarSpec. */
export interface SidebarItemSpec {
  key: string;       // must exist in vocabulary
  label?: string;    // optional personal rename — display-only
  visible: boolean;  // false = hidden from this user's sidebar only
}

/**
 * The sidebar spec — stored once per user (not per-domain) at dsi:sidebar-spec.
 * Independent of all ViewSpecs; the renderer draws from this, not hardcoded nav.
 */
export interface SidebarSpec {
  version: '1.0';
  /**
   * false = collapse the ENTIRE sidebar panel (not rendered at all).
   * Defaults to true. Set to true to restore after hiding.
   */
  visible?: boolean;
  items: SidebarItemSpec[];
}
