import { z } from 'zod';
import type { AppVocabulary } from './app-vocabulary';

/**
 * Factory that builds a fully concrete Zod schema from any AppVocabulary.
 * Called once at server startup per domain; the resulting schema is frozen
 * and reused for every validation call.
 *
 * The engine contains no layout names, field keys, or domain strings.
 * All vocabulary is derived from the injected AppVocabulary.
 */
export function buildViewSpecSchema(vocab: AppVocabulary) {
  // Derive typed sub-enums from vocabulary flags.
  // Zod requires at least one element for z.enum(); validated at runtime below.
  const layoutNames = vocab.layouts.map((l) => l.name) as [string, ...string[]];
  const fieldKeys = vocab.fields.map((f) => f.key) as [string, ...string[]];

  const groupableKeys = vocab.fields
    .filter((f) => f.groupable)
    .map((f) => f.key);

  const filterableKeys = vocab.fields
    .filter((f) => f.filterable)
    .map((f) => f.key);

  const sortableKeys = vocab.fields
    .filter((f) => f.sortable)
    .map((f) => f.key);

  // Layouts that structurally require a groupBy (e.g. kanban).
  // The rule is expressed in terms of the vocab flag, not the name.
  const groupRequiredLayouts = vocab.layouts
    .filter((l) => l.requiresGroupBy)
    .map((l) => l.name);

  if (vocab.layouts.length === 0) {
    throw new Error('AppVocabulary must declare at least one layout');
  }
  if (vocab.fields.length === 0) {
    throw new Error('AppVocabulary must declare at least one field');
  }

  // Engine-level constants: filter operators and sort direction are not
  // domain-specific — they are pure display predicates.
  const FilterOpSchema = z.enum(['eq', 'neq', 'in', 'contains']);
  const SortDirectionSchema = z.enum(['asc', 'desc']);

  const FieldSpecSchema = z.object({
    key: z.enum(fieldKeys),
    /** Personal display label — renames the column heading for this user only. */
    label: z.string().max(40).optional(),
    visible: z.boolean().default(true),
  });

  const FilterClauseSchema = z.object({
    field: filterableKeys.length > 0
      ? z.enum(filterableKeys as [string, ...string[]])
      : z.never(),
    op: FilterOpSchema,
    value: z.union([z.string(), z.array(z.string()).min(1)]),
  });

  const SortClauseSchema = z.object({
    field: sortableKeys.length > 0
      ? z.enum(sortableKeys as [string, ...string[]])
      : z.never(),
    direction: SortDirectionSchema,
  });

  const baseSchema = z.object({
    version: z.literal('1.0'),

    /** Short user-facing label generated by the agent. */
    name: z.string().max(80).optional(),

    /** Agent's plain-English rationale — helpful for debugging prompts. */
    description: z.string().max(300).optional(),

    layout: z.enum(layoutNames),

    /**
     * Ordered field list. Order drives column/card rendering order.
     * No duplicate keys allowed.
     */
    fields: z
      .array(FieldSpecSchema)
      .min(1)
      .max(fieldKeys.length)
      .refine(
        (fs) => new Set(fs.map((f) => f.key)).size === fs.length,
        { message: 'fields must not contain duplicate keys' },
      ),

    /**
     * Optional grouping key. Required when the chosen layout has
     * requiresGroupBy: true in the AppVocabulary.
     */
    groupBy: groupableKeys.length > 0
      ? z.enum(groupableKeys as [string, ...string[]]).optional()
      : z.undefined(),

    /**
     * Display-only filter predicates. AND'd together.
     * These HIDE items from view — they never delete or mutate data.
     */
    filters: filterableKeys.length > 0
      ? z.array(FilterClauseSchema).max(10).default([])
      : z.array(z.never()).default([]),

    sort: sortableKeys.length > 0
      ? SortClauseSchema.optional()
      : z.undefined(),

    limit: z.number().int().min(1).max(200).default(100),
  });

  // Cross-field structural rule: any layout with requiresGroupBy: true in
  // the vocabulary must have a groupBy present in the spec.
  // The engine expresses this rule without naming the layout.
  if (groupRequiredLayouts.length === 0) {
    return baseSchema;
  }

  return baseSchema.refine(
    (spec) =>
      !groupRequiredLayouts.includes(spec.layout) ||
      spec.groupBy !== undefined,
    {
      message: `layouts [${groupRequiredLayouts.join(', ')}] require a groupBy field`,
      path: ['groupBy'],
    },
  );
}

export type ViewSpecSchema = ReturnType<typeof buildViewSpecSchema>;
